### ISSUE TITLE
Suggestion - Increase in font size of 'code' on the web page

### ISSUE THREAD

**Issue by sudo-batman** [manwar/perlweeklychallenge#42] opened 2019-12-19 09:50 UTC
While going through the code block on the web page I found the font size is little smaller which is making it difficult to read on the desktop machine. However on mobile it is good.
e.g. https://perlweeklychallenge.org/blog/advent-calendar-2019-12-19/

If you look at the code part on desktop machine it is quite smaller. In css I can see 'pre' is '87.5%'. Maybe a 100% or 12px would be a better choice.

Screenshot for reference purpose.
![perlweekly](https://user-images.githubusercontent.com/23376158/71163354-f0cffc80-2272-11ea-89e7-038e5936b970.PNG)

**Comment by rjt-pl** [comment] 2020-03-30 10:17
Here is a current screenshot, showing Perl and plaintext code blocks:

![code_font](https://user-images.githubusercontent.com/3000446/77901676-41290400-723d-11ea-9b77-1bc5b98c44c6.png)

**Comment by manwar** [comment] 2020-03-30 11:14
Does that mean, the issue is resolved now?

**Comment by rjt-pl** [comment] 2020-03-30 11:16
From my point of view, yes. Unless you or @sudo-batman feel I need to tweak it further of course.

**Comment by manwar** [comment] 2020-03-30 11:22
To be honest, I am happy after your tweak. Lets see what @sudo-batman had to say?

**Comment by sudo-batman** [comment] 2020-03-31 05:49
Looks good to me. Thank you

**Comment by manwar** [comment] 2020-03-31 07:34
It is safe to close the issue now as confirmed by @sudo-batman.
Thanks @rjt-pl for your patch.

**Closed by manwar** 2020-03-31 07:34 UTC
